version: '2'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin
    env_file: ./.env
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - "8090:80"
    networks:
      - mysql-phpmyadmin

  backend:
    build:
      context: ./backend/
    env_file: ./.env
    command: /usr/app/node_modules/.bin/nodemon server.js
    depends_on:
      - mysqldb
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend
      - frontend
      - mysql-phpmyadmin

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    networks:
      - frontend

volumes: 
  db_data:

networks:
  mysql-phpmyadmin:
  backend:
  frontend:
